development:
  adapter: mysql
  database: lokii_development
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: lokii_test
  username: root
  password:
  host: localhost

